### ISSUE TITLE
请问是SASS服务还是SAAS服务呢？

### ISSUE THREAD

**Issue by JiayingZeng** [ychow/ionic-guide#1]
> 除了带有SASS服务和各种各样的AngularJS拓展（可选）之外，还有大量的组件。

不明白SASS服务是什么，google出来的都是在解释 sass服务
`Software as a Service，缩写为 SaaS，软件即服务`
https://zh.wikipedia.org/wiki/%E8%BD%AF%E4%BB%B6%E5%8D%B3%E6%9C%8D%E5%8A%A1

**Comment by ychow** [comment]
@JiayingZeng 不好意思，这里的SASS是指预处理器。http://sass-lang.com/
